// <auto-generated />
using System;
using EarlySignalSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EarlySignalSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715201414_AddTechnicalAssessments")]
    partial class AddTechnicalAssessments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EarlySignalSystem.Models.CompanyPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("PickedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RunLogId")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sentiment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RunLogId");

                    b.ToTable("CompanyPicks");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.CompanyPickSignal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyPickId")
                        .HasColumnType("int");

                    b.Property<int>("SignalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPickId");

                    b.HasIndex("SignalId");

                    b.ToTable("CompanyPickSignals");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.CumulativeScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstSignalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LatestPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("LatestPriceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PriceChangePercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("PriceOnFirstSignalDate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignalCount")
                        .HasColumnType("int");

                    b.Property<int>("SignalDiversity")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VelocityLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CumulativeScores");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.RunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignalsCollected")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RunLogs");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.SectorScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Rationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RunLogId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RunLogId");

                    b.ToTable("SectorScores");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.ShortlistSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyRank")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CumulativeScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Rationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScanNumber")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sentiment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignalCount")
                        .HasColumnType("int");

                    b.Property<int>("SignalDiversity")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VelocityLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShortlistSnapshots");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RunLogId")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RunLogId");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.TechnicalAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Assessment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MACDSignal")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("RSI")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalAssessments");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.CompanyPick", b =>
                {
                    b.HasOne("EarlySignalSystem.Models.RunLog", "RunLog")
                        .WithMany("CompanyPicks")
                        .HasForeignKey("RunLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RunLog");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.CompanyPickSignal", b =>
                {
                    b.HasOne("EarlySignalSystem.Models.CompanyPick", "CompanyPick")
                        .WithMany("CompanyPickSignals")
                        .HasForeignKey("CompanyPickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EarlySignalSystem.Models.Signal", "Signal")
                        .WithMany()
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyPick");

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.SectorScore", b =>
                {
                    b.HasOne("EarlySignalSystem.Models.RunLog", "RunLog")
                        .WithMany("SectorScores")
                        .HasForeignKey("RunLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RunLog");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.Signal", b =>
                {
                    b.HasOne("EarlySignalSystem.Models.RunLog", "RunLog")
                        .WithMany("Signals")
                        .HasForeignKey("RunLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RunLog");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.CompanyPick", b =>
                {
                    b.Navigation("CompanyPickSignals");
                });

            modelBuilder.Entity("EarlySignalSystem.Models.RunLog", b =>
                {
                    b.Navigation("CompanyPicks");

                    b.Navigation("SectorScores");

                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
